### ISSUE TITLE
Possibility to update vectors

### ISSUE THREAD

**Issue by lboudard** [pixelogik/NearPy#42]
Hi,

I think it would be very useful to have possibility to update vectors index.
Typically, a CF application would need to update movies/users vectors regularilly as users buy/see movies. From my undertanding of the model, it would require 1) vectorize movie before update 2) retrieve buckets containing movie vectors and remove it from set 3) vectorize movie after update and push it.
While it's certainly doable, there might be some more intermediary data structures that could help in that task.

Thanks!

**Comment by pixelogik** [comment]
Sounds cool, but I do not have time for this currently. If you want to participate, let me know.

**Comment by MaxwellRebo** [comment]
Any resolution to this?

**Comment by MaxwellRebo** [comment]
@lboudard this has been here for a bit, any interest in taking it back up?

**Comment by pixelogik** [comment]
I still don't have time, sorry. Too busy with work. But if you guys wanna contribute I can add you as collaborators.

**Comment by adityapatadia** [comment]
I will look after PR if someone is ready to send.


On 23 June 2016 at 2:29:31 PM, Ole (notifications@github.com) wrote:

I still don't have time, sorry. Too busy with work. But if you guys wanna
contribute I can add you as collaborators.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/pixelogik/NearPy/issues/42#issuecomment-227990130>, or mute
the thread
<https://github.com/notifications/unsubscribe/ABCUmQgEothfaC-MVSueGIZc5WOGLk3Jks5qOkrvgaJpZM4Gqhmu>
.

**Comment by neerajBaji** [comment]
Hi,

I am working on a similar CF problem whereby I would need to update the index. Can you sign me on as a contributor? I will give this a shot.

**Comment by erramuzpe** [comment]
Hi @pixelogik , @adityapatadia , @neerajBaji and @MaxwellRebo 

I'm also interested in this. The way of doing it should be to look for a given index and deleting both the index and the vector corresponding to that index. Then, the update will come through a new index operation. Seems easy, but I'm not sure where to start from. 

cheers!

**Comment by erramuzpe** [comment]
Related to #27 @audy

**Comment by erramuzpe** [comment]
I think I have it! It would be nice if someone could do this for RedisStorage too :+1:
